### ISSUE TITLE
Clarify Sync vs Async usage 

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/langchain-google-alloydb-pg-python#271]
The implementations in this library contain both sync and async interfaces. The samples in the [README](https://github.com/googleapis/langchain-google-alloydb-pg-python?tab=readme-ov-file#example-usage) demonstrate sync usage, but the samples in the migration guides demonstrate async usage.

We should do 2 things:
1. Add a section to the README that discusses sync vs async usage, and specifically shows the users how to convert usage back and forth. 
2. Standardize all of our examples / samples in the repo to use the same interface, and link to this section for details how to make similar code with the opposite interface.

**Comment by averikitsch** [comment]
Updating to use sync in copy and paste tutorials and adding notes to ReadMe
